# Generated by Django 4.1.4 on 2023-05-29 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Sizes', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Current_Stock', models.IntegerField()),
                ('Max_Stock', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Delete_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product_crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Sizes', models.CharField(choices=[('20 x 20', '20 x 20'), ('20 x 60', '20 x 60'), ('30 x 30', '30 x 30'), ('30 x 60', '30 x 60'), ('40 x 40', '40 x 40'), ('60 x 30', '60 x 30'), ('n/a', 'N/A')], default='12 x 30', max_length=50, null=True)),
                ('Category', models.CharField(choices=[('adhesive', 'Adhesive'), ('porcelain', 'Porcelain'), ('ceramic', 'Ceramic'), ('skimcoat', 'Skimcoat'), ('sanitaryware ', 'Sanitary ware')], default='Adhesive', max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Current_Stock', models.IntegerField()),
                ('Max_Stock', models.IntegerField()),
                ('Status', models.CharField(choices=[('available', 'Available'), ('notavailable', 'Not Available')], max_length=50)),
                ('Image', models.ImageField(upload_to='allimg')),
                ('Date_Added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
