# Generated by Django 4.1.4 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_crud',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
    ]
