# Generated by Django 4.1.4 on 2022-12-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customersname', models.CharField(max_length=20)),
                ('Customersnumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Add', models.CharField(max_length=50)),
            ],
        ),
    ]
