# Generated by Django 4.1.4 on 2022-12-27 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CrudSamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
