# Generated by Django 4.1.4 on 2022-12-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudSamp', '0002_alter_customers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
