# Generated by Django 4.1.3 on 2023-05-19 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Fname', models.CharField(max_length=50)),
                ('customer_Middlename', models.CharField(max_length=50, null=True)),
                ('customer_Lname', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')])),
            ],
        ),
    ]
