# Generated by Django 4.1.4 on 2022-12-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='person',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
