# Generated by Django 4.1.4 on 2022-12-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_remove_feedback_date_created_remove_feedback_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
