# Generated by Django 4.1.4 on 2022-12-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewlist',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
