# Generated by Django 4.1.4 on 2023-01-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_customers_crud_delete_createnewlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customers_crud',
            name='CustomersAdd',
            field=models.CharField(max_length=50),
        ),
    ]
