# Generated by Django 4.1.4 on 2023-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_product_crud_alter_customers_crud_customersadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_crud',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
