# Generated by Django 4.1.4 on 2023-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0009_alter_product_crud_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_crud',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
