# Generated by Django 4.1.4 on 2023-01-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0010_alter_product_crud_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_crud',
            old_name='price',
            new_name='Price',
        ),
    ]
