# Generated by Django 4.1.4 on 2023-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0011_rename_price_product_crud_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_crud',
            name='Stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
