# Generated by Django 4.1.4 on 2023-01-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0012_alter_product_crud_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Deleted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.product_crud')),
            ],
        ),
    ]
