# Generated by Django 4.1.4 on 2023-01-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0013_product_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_archive',
            name='Deleted',
        ),
    ]
