# Generated by Django 4.1.4 on 2023-01-07 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0014_remove_product_archive_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_archive',
            name='Delete_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
