# Generated by Django 4.1.4 on 2023-01-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0016_useradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Guestpage')),
                ('Updload_at', models.DateTimeField(auto_now=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
