# Generated by Django 4.1.4 on 2023-01-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0018_photoup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoup',
            name='Description',
        ),
        migrations.AlterField(
            model_name='photoup',
            name='Updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photoup',
            name='Updload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
