# Generated by Django 4.1.4 on 2023-01-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0019_remove_photoup_description_alter_photoup_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoup',
            name='Image',
            field=models.ImageField(upload_to='Guestpage/Tilesimg'),
        ),
    ]
