# Generated by Django 4.1.4 on 2023-01-15 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0020_alter_photoup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoup',
            name='Updated_at',
        ),
        migrations.AddField(
            model_name='photoup',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photoup',
            name='Updload_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
