# Generated by Django 4.1.4 on 2023-01-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0021_remove_photoup_updated_at_photoup_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoup',
            name='Category',
        ),
    ]
