# Generated by Django 4.1.4 on 2023-01-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0024_alter_photoup_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoup',
            name='Category',
        ),
    ]
