# Generated by Django 4.1.4 on 2023-01-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0027_alter_photoup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoup',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
