# Generated by Django 4.1.4 on 2023-01-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0032_alter_product_crud_category_alter_product_crud_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_crud',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_crud',
            name='Size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
