# Generated by Django 4.1.4 on 2023-01-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0033_alter_product_crud_category_alter_product_crud_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoup',
            name='Description',
        ),
    ]
