# Generated by Django 4.1.4 on 2023-01-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0034_remove_photoup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUPporcelain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=50)),
                ('Size', models.CharField(blank=True, choices=[('12 x 30', '12 x 30'), ('247 x 97', '247 x 97'), ('20 x 30', '20 x 30')], max_length=50, null=True)),
                ('Category', models.CharField(choices=[('adhesive', 'Adhesive'), ('porcelain', 'Porcelain'), ('ceramic', 'Ceramic'), ('skimcoat', 'Skimcoat'), ('sanitaryware ', 'Sanitary ware')], max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='porcelain_img')),
                ('Updload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
