# Generated by Django 4.1.4 on 2023-01-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0035_photoupporcelain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoupporcelain',
            old_name='Category',
            new_name='Category_p',
        ),
        migrations.RenameField(
            model_name='photoupporcelain',
            old_name='Image',
            new_name='Image_p',
        ),
        migrations.RenameField(
            model_name='photoupporcelain',
            old_name='Itemname',
            new_name='Itemname_p',
        ),
        migrations.RenameField(
            model_name='photoupporcelain',
            old_name='Size',
            new_name='Size_p',
        ),
    ]
