# Generated by Django 4.1.4 on 2023-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0036_rename_category_photoupporcelain_category_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUPCeramic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname_c', models.CharField(max_length=50)),
                ('Size_c', models.CharField(blank=True, choices=[('12 x 30', '12 x 30'), ('247 x 97', '247 x 97'), ('20 x 30', '20 x 30')], max_length=50, null=True)),
                ('Category_c', models.CharField(choices=[('adhesive', 'Adhesive'), ('porcelain', 'Porcelain'), ('ceramic', 'Ceramic'), ('skimcoat', 'Skimcoat'), ('sanitaryware ', 'Sanitary ware')], max_length=50)),
                ('Image_c', models.ImageField(blank=True, null=True, upload_to='uploadedimg')),
                ('Updload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
