# Generated by Django 4.1.4 on 2023-01-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0040_photoupsanitary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoupsanitary',
            old_name='Category_S',
            new_name='Category_Sa',
        ),
        migrations.RenameField(
            model_name='photoupsanitary',
            old_name='Image_S',
            new_name='Image_Sa',
        ),
        migrations.RenameField(
            model_name='photoupsanitary',
            old_name='Itemname_S',
            new_name='Itemname_Sa',
        ),
        migrations.RenameField(
            model_name='photoupsanitary',
            old_name='Size_S',
            new_name='Size_Sa',
        ),
    ]
