# Generated by Django 4.1.4 on 2023-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0041_rename_category_s_photoupsanitary_category_sa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupsanitary',
            name='Image_Sa',
            field=models.ImageField(blank=True, null=True, upload_to='sanitary_img'),
        ),
        migrations.AlterField(
            model_name='photoupskimcoat',
            name='Image_S',
            field=models.ImageField(blank=True, null=True, upload_to='skim_img'),
        ),
    ]
