# Generated by Django 4.1.4 on 2023-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0042_alter_photoupsanitary_image_sa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoup',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
        migrations.AlterField(
            model_name='photoupceramic',
            name='Image_c',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
        migrations.AlterField(
            model_name='photoupporcelain',
            name='Image_p',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
        migrations.AlterField(
            model_name='photoupsanitary',
            name='Image_Sa',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
        migrations.AlterField(
            model_name='photoupskimcoat',
            name='Image_S',
            field=models.ImageField(blank=True, null=True, upload_to='allimg'),
        ),
    ]
