# Generated by Django 4.1.4 on 2023-01-27 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainweb', '0044_alter_useradmin_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdmin',
            new_name='CustomUser',
        ),
    ]
