# Generated by Django 4.1.4 on 2023-01-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0048_remove_myuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
