# Generated by Django 4.1.4 on 2023-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0050_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
