# Generated by Django 4.1.4 on 2023-03-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0051_alter_staff_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
