# Generated by Django 4.1.4 on 2023-03-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0052_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoUPCeramic',
        ),
        migrations.DeleteModel(
            name='PhotoUPporcelain',
        ),
        migrations.DeleteModel(
            name='PhotoUPSanitary',
        ),
        migrations.DeleteModel(
            name='PhotoUPSkimcoat',
        ),
    ]
