# Generated by Django 4.1.4 on 2023-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartquantity',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
