# Generated by Django 4.1.4 on 2023-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0002_alter_cartquantity_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartquantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
